export const movieData = [
    {
        id:Math.random(),
        title:"Oxygéne",
        dateDeSortie :2021,
        description:"Dans O2,une jeune femme se réveille seule dans une capsule cryogénique.Elle ne sait plus qui elle + ",
        posterUrl:"https://www.au-cine.com/wp-content/uploads/2021/04/Oxyge%CC%80ne-Affiche-e1619021241464.jpeg",
        rating:6.5,
        duration:"100 min",
        genre: "Nouveaux / Science-Fiction / Thriller",
        director:"Alexandre Aja",
        trailer:"https://www.youtube.com/watch?v=8IqXgZd-P98"
    },
    {
        id:Math.random(),
        title:"Mortal kombat",
        dateDeSortie:2021,
        description:"Lorsque les plus grands champions de la Terre sont appelés à combattre les ennemis de l'Autre Monde +",
        posterUrl:"https://wallpapercave.com/wp/wp8626135.jpg",
        rating:6.2,
        duration:"103 min",
        genre:"Nouveaux / Action / Aventure / Fantastique",
        director:"Simon McQuoid",
        trailer:"https://www.youtube.com/watch?v=NYH2sLid0Zc"
    },
    {
        id:Math.random(),
        title:"Le gang Jönsson",
        dateDeSortie:2020,
        description:"Après avoir purgé sa peine, Charles Ingvar « Sickan » Jönsson retourne à la vie civile avec un nouveau +",
        posterUrl:"https://imgr.cineserie.com/2019/09/1581357.jpg?imgeng=/f_jpg/cmpr_0/w_1400/h_2100/m_cropbox&ver=1",
        rating:3.9,
        duration:"122 min",
        genre:"Nouveaux / Action / Aventure / Fantastique",
        director:"Tomas Alfredson",
        trailer:"https://www.youtube.com/watch?v=rqX_n73BnXY"
    },
    {
        id:Math.random(),
        title:"Hamilton",
        dateDeSortie:2020,
        description:"Captation de la célèbre comédie musicale de Broadway récompensée par 11 Tony, Grammy et Olivier Awards +",
        posterUrl:"https://upload.wikimedia.org/wikipedia/en/c/c3/Hamilton_Disney%2B_poster_2020.jpg",
        rating:8.5,
        duration:"160 min",
        genre:"VOSTFR / Drame",
        director:"Thomas Kail",
        trailer:"https://www.youtube.com/watch?v=DSCKfXpAGHc"
    },
    {
        id:Math.random(),
        title:"Fast color",
        dateDeSortie:2019,
        description:"Une jeune femme est obligée de fuir quand ses capacités surhumaines sont découvertes. Des années après avoir +",
        posterUrl:"https://occ-0-300-299.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABR_IwjOd9hSlV7YX9nvVbgG9PF9QEYkHck2v3oMKIy2m2Pnd-P2ufs1tZ55_N2fLPKf7oFHjNKXOmsOrc1rl7UVixMg5.jpg",
        rating:6.1,
        duration:"100 min",
        genre:"Drame / Science-Fiction / Thriller",
        director:" Julia Hart",
        trailer:"https://www.youtube.com/watch?v=tySUZIiXObc&pp=ugMICgJmchABGAE%3D"
    },
    {
        id:Math.random(),
        title:"Bulletproof 2",
        dateDeSortie:2020,
        description:"L'agent spécial Jack Carter assume à contrecœur l'identité du criminel Archie Moses pour éliminer une puissante +",
        posterUrl:"https://media.senscritique.com/media/000019418796/source_big/Bulletproof_2.jpg",
        rating:3.5,
        duration:"97 min",
        genre:" Action / Comedie / Crime",
        director:"Don Michael Paul",
        trailer:"https://www.youtube.com/watch?v=d-2rYQhoUDo"
    },
    {
        id:Math.random(),
        title:"Righteous Villains",
        dateDeSortie:2020,
        description:"A modern day tale of good vs evil, secret societies, sorcery and Satan",
        posterUrl:"https://img.yts.mx/assets/images/movies/righteous_villains_2020/large-cover.jpg",
        rating:5.2,
        duration:"76 min",
        genre:"Thriller / Crime",
        director:"Savvas D. Michael",
        trailer:"https://www.youtube.com/watch?v=paxa_Wa6a-A"
    },
    {
        id:Math.random(),
        title:"French Exit ",
        dateDeSortie:2021,
        description:"Frances Price est une mondaine sans le sou de Manhattan. Elle avait planifié de mourir avant que son argent ne soit +",
        posterUrl:"https://www.dvdsreleasedates.com/posters/800/F/French-Exit-2020-movie-poster.jpg",
        rating:6.1,
        duration:"113 min",
        genre:"Comedie / Drame",
        director:"Azazzal Jacobs",
        trailer:"https://www.youtube.com/watch?v=bqMJeE15YiA"
    },
    {
        id:Math.random(),
        title:"Those Who Wish Me Dead ",
        dateDeSortie:2021,
        description:"Un adolescent de quatorze ans est témoin d'un meurtre brutal. Il reçoit une fausse identité. Il est transféré +",
        posterUrl:"https://www.joblo.com/assets/images/joblo/posters/2021/04/rsz_those-who-wish-me-dead-poster.jpg",
        rating:1,
        duration:"100 min",
        genre:"VOSTFR / Action / Drame / Thriller",
        director:"Taylor Sheridan ",
        trailer:"https://www.youtube.com/watch?v=sV6VNNjBkcE"
    },
    {
        id:Math.random(),
        title:"Lucky ",
        dateDeSortie:2020,
        description:"Une femme de banlieue se bat pour être crue lorsqu’elle se retrouve traquée par une figure masquée et menaçante +",
        posterUrl:"https://resizing.flixster.com/_KzZ2FBUaJXh8CuOyTNCqHaq-IQ=/ems.ZW1zLXByZC1hc3NldHMvbW92aWVzLzk0NWQ5ZmJmLWQwZmQtNDlmMS1hZmNkLWFhMGZkNmZmM2JjMC5qcGc=",
        rating:5.1,
        duration:"83 min ",
        genre:"VOSTFR / Epouvante-horreur / Thriller",
        director:"Natasha Kermani",
        trailer:"https://www.youtube.com/watch?v=5TC2QkqqtgQ"
    },
    {
        id:Math.random(),
        title:"Above the Shadows ",
        dateDeSortie:2019,
        description:"A young woman who has faded to the point of becoming invisible must find her way back with the help of the one man who can see her",
        posterUrl:"https://www.themoviedb.org/t/p/original/3FrGhwhyZdNtdZRXS6jQbFw9KYB.jpg",
        rating:3,
        duration:"111 min",
        genre:"VOSTFR / Fantastique / Romance",
        director:"Claudia Myers",
        trailer:"https://www.youtube.com/watch?v=AAcplHUDzyI&pp=ugMICgJmchABGAE%3D"
    },
    {
        id:Math.random(),
        title:"Stage Mother",
        dateDeSortie:2020,
        description:"L'histoire de Maybelline, une directrice de chœur d'église conservatrice du Texas, qui hérite de la boîte +",
        posterUrl:"https://www.themoviedb.org/t/p/original/li8tyzpu5RglqFVklMO9UvpaIYo.jpg",
        rating:6.5,
        duration:"93 min",
        genre:"Thom Fitzgerald",
        director:"Comedie / Drame",
        trailer:"https://www.youtube.com/watch?v=-AvSoHSYLeA"
    }
]
